### ISSUE TITLE
Please add some documentation on how to use this

### ISSUE THREAD

**Issue by Daniel-GabrielN** [meziantou/Meziantou.DotNet.CodingStandard#69]
Hi Gérald, 
How can I get this to work in a new or existing solution? 
It seems like installing the nuget is not enough.

Kind regards,
Gabriel

**Comment by meziantou** [comment]
> It seems like installing the nuget is not enough.

Installing the package should be enough. What doesn't work?

**Comment by meziantou** [comment]
The editorconfig are in the NuGet package and provided to the compiler using MSBuild items: https://github.com/meziantou/Meziantou.DotNet.CodingStandard/blob/7aae7c86924685b5bcd0bd3d23cd86cbc882c73b/src/build/Meziantou.DotNet.CodingStandard.props#L24

The analyzers are added as dependencies of the CodingStandard package https://github.com/meziantou/Meziantou.DotNet.CodingStandard/blob/7aae7c86924685b5bcd0bd3d23cd86cbc882c73b/Meziantou.DotNet.CodingStandard.nuspec#L21-L22

You can read more about this here: https://www.meziantou.net/sharing-coding-style-and-roslyn-analyzers-across-projects.htm

**Comment by Daniel-GabrielN** [comment]
Thank you Gérald, I understand now.
I've tried again with some code full of issues and the build warnings were there after installing the nuget.
